# -*- coding: utf-8 -*-
"""PYT-101 - Variables and Data Types

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yDXwmmFyXpLt1CYarLbPReC9HtKZgLTQ

# **1) Ticket Booth Tally**

You're creating an app that adds up pre-sold tickets to an event stored on a text file, but something is going wrong and the total is completely off.

Fix the code so it returns the correct number of pre-sold tickets:
"""

def ticket_total():
    presale_a = "120"
    presale_b = "35"

    return int(presale_a) + int(presale_b)

print(ticket_total())
# The issue with the code is that presale_a and presale_b were stored as strings inside of parenthesis. Python reads this as (12035) instead of (120+35). To fix this issue you must convert the strings to integers before adding them.

"""# **2) Precise Average**

A scientific tool you're working on should compute the average of two readings, but it keeps returning a whole number rather than a decimal.

Fix the code so the average is given as a precise value:
"""

def average_reading():
    a = 7
    b = 2
    avg = (a + b) / 2
    return avg

print(average_reading())
# The issue with this code is that the code uses floor division (//) which rounds the result down to the nearest whole number, dropping the decimal. To fix this issue, change to the standard division symbol (/).

"""# **3) Access Control Flag**

You're working on a moderation panel that interacts with other tools expecting boolean values, but it's showing numeric rather than truth values.

Fix the code so the correct values are returned.
"""

def can_delete():
    is_admin = False
    is_owner = True
    return is_admin or is_owner

print(can_delete())
# The issue with this code is that the code is using (0 and 1) instead of Boolean true values like (True or False). Replace (0 and 1) with Boolean values.

"""# **4) Receipt Line**

A POS system you're working on is supposed to print a single line on the receipt, but something is going wrong and it keeps crashing.

Fix the code so the system correctly prints the subtotal.
"""

def receipt_line():
    subtotal = 48
    return "Subtotal: $" + str(subtotal)

print(receipt_line())
# The code shows TypeError because it is trying to combine an integer (subtotal) and a string using the + sign. To fix the code, convert the integer to a string using str() or an f-string.

"""# **5) Countdown Timer**

You're working on a timer that should count down from a given number of seconds, but currently it errors out.

Fix the code so the loop runs correctly and prints each number.
"""

def countdown():
    seconds = 5
    for s in range(seconds, 0, -1):
        print(s)
    return "Done!"

print(countdown())
# The bug is that seconds is set to a float (5.0). Python's range() function requires integers for its arguments. Passing a float causes a TypeError.

"""# **6) Indices from User Input**

You're working on a photo app where users type which photo they want to view, but something is causing the program to crash.

Fix the code so it returns the correct photo by index.
"""

def pick_photo():
    photos = ("sun", "moon", "stars")
    index = "2"
    return photos[index]

print(pick_photo())
# There are two issues with this code:
  #~ Index is assigned a string value ("2"). Python list/tuple indices must be integers.
  #~ The code attempts to access the index 2 of a 3-item tuple ("sun", "moon", "stars"). Because Python uses zero-based indexing, index 2 is "stars". However, if a user inputs "3" thinking it means the third photo, it will cause an IndexError.
  #~ To fix the code, convert the index to an integer and subtract 1 to account for zero-based indexing.

"""# **7) Cart Total from Mixed Types**

The shopping app you're working on is currently crashing instead of returning the total price of items in the user's cart.

Fix the code so it correctly returns the total cart price.
"""

def cart_total():
    items = ["12.50", 7.25, "3.00"]
    total = 0
    for price in items:
        total += float(price)
    return total

print(cart_total())
# The code is crashing because the items list contains a mixture of strings ("12.50", "3.00") and a float (7.25). Python cannot mathematically add a string to a number, resulting in a TypeError.
# To fix this error in the code, convert each item to a float using float() inside the loop before adding it to the total.

"""# **8) Laugh Counter**

You're working on a joke bot that should print “ha” three times, but something is going terribly wrong.

Fix the code so it prints "hahaha" without errors.
"""

def laugh():
    base = "ha"
    times = int("3")
    return base * times

print(laugh())
# The error in this code is that times is assigned a string value ("3"). In Python, you can multiply a string by an integer to repeat it, but multiplying a string by another string ("ha" * "3") causes a TypeError.
# To fix this error, convert the times variable into an integer using int().

"""# **9) Access List**

Your API only allows certain numeric user IDs, but an ID you know to be correct isn't allowing access.

Fix the code so the membership test correctly returns True.
"""

def can_access():
    allowed_ids = {42, 64, 128}
    user_id = int("42")
    return user_id in allowed_ids

print(can_access())
# The error with this code is a type mismatch. The user_id is a string ("42"), but the allowed_ids set contains integers (42, 64, 128). In Python, a string will never match an integer, so the membership test evaluates to False.
# To fix the code, convert the user_id to an integer using int() before performing the in check.

"""# **10) Feature Flags**

Thew app you're working on handles toggles as strings of "0" or "1," but a function downstream is expected to specifically return True or False.

Fix the code so the function returns the proper boolean (True) for the current flag.
"""

def is_enabled():
    flag = "1"
    return flag == "1"

print(is_enabled())
# The issue with this code is that the flag is a string ("1"), but the function is supposed to return a Boolean (True or False). The expression flag or False returns the string "1" instead of the Boolean value True.
# To fix this code, use a direct comparison (flag == "1") to guarantee that the function returns a strict boolean value (True or False).